---
application:
  name: "portfolio"
  project: "nodetest"
  organization: "fabiokleis"
databases:
- type: "MONGODB"
  name: "blog"
  version: "4.4"
routers:
- name: "main-portfolio"
  routes:
  - application_name: "portfolio"
    paths:
    - "/*"
